# Generated by Django 4.1.3 on 2022-11-22 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_supplements_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
